/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ResultRouteImport } from './routes/result'
import { Route as CheckRouteImport } from './routes/check'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiseaseDiseaseIdRouteImport } from './routes/disease.$diseaseId'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseDiseaseIdRoute = DiseaseDiseaseIdRouteImport.update({
  id: '/disease/$diseaseId',
  path: '/disease/$diseaseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/check': typeof CheckRoute
  '/result': typeof ResultRoute
  '/sources': typeof SourcesRoute
  '/disease/$diseaseId': typeof DiseaseDiseaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/check': typeof CheckRoute
  '/result': typeof ResultRoute
  '/sources': typeof SourcesRoute
  '/disease/$diseaseId': typeof DiseaseDiseaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/check': typeof CheckRoute
  '/result': typeof ResultRoute
  '/sources': typeof SourcesRoute
  '/disease/$diseaseId': typeof DiseaseDiseaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/check'
    | '/result'
    | '/sources'
    | '/disease/$diseaseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/check'
    | '/result'
    | '/sources'
    | '/disease/$diseaseId'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/check'
    | '/result'
    | '/sources'
    | '/disease/$diseaseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CheckRoute: typeof CheckRoute
  ResultRoute: typeof ResultRoute
  SourcesRoute: typeof SourcesRoute
  DiseaseDiseaseIdRoute: typeof DiseaseDiseaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease/$diseaseId': {
      id: '/disease/$diseaseId'
      path: '/disease/$diseaseId'
      fullPath: '/disease/$diseaseId'
      preLoaderRoute: typeof DiseaseDiseaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CheckRoute: CheckRoute,
  ResultRoute: ResultRoute,
  SourcesRoute: SourcesRoute,
  DiseaseDiseaseIdRoute: DiseaseDiseaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
